server:
  port: 8040
spring:
  application:
    name: order
  datasource:
    name: orderingsystem
    url: jdbc:mysql://172.16.55.163:3306/ordering?useUnicode=true&characterEncoding=UTF-8
    username: trainning
    password: trainning
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.55.39:6018/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.gm.entity